# University Student Success Analytics Project
## Author
Nicholas Guthery  
Business Data Analytics Student  
W.P. Carey School of Buusiness, Arizona State University

## Data Cleaning Notebook
The purpose of this notebook is to clean and prepare a University Student dataset for analysis.

The cleaning process includes:
- Identifying mussing values
- Removing duplicates
- Validating data types
- Correcting data quality issues

#### Upload Dataset
The dataset is stored on my computerm so I need to upload it to Colab.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student_success_messy.csv to student_success_messy.csv

#### Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

# Display all rows
pd.set_option('display.max_rows', None)

#### Load Dataset

In [ ]:
df = pd.read_csv('student_success_messy.csv')

df.head()

,StudentID,Gender,Age,ParentEducation,InternetAccess,StudyHoursPerWeek,Absences,PriorFailures,FinalGrade
0,2001,male,20,Associate,NaN,17.0,27,2,49.0
1,2002,Female,18,High School,No,10.0,28,0,39.0
2,2003,male,20,Master,No,15.0,22,1,69.0
3,2004,Female,18,Master,NaN,17.0,23,1,69.0
4,2005,FEMALE,20,Master,No,12.0,8,2,46.0

#### Dataset Inspection

In [ ]:
# Dataset dimesnions
print("Dataset Dimensions")
print("Rows and Columns: ", df.shape)
print("")

# Column names
print("Column Names")
print(df.columns)
print("")

# Data types
print("Data Types")
print(df.dtypes)
print("")

# Summary Statistics
print("Summary Statistics")
print(df.describe())

Dataset Dimensions
Rows and Columns:  (315, 9)

Column Names
Index(['StudentID', 'Gender', 'Age', 'ParentEducation', 'InternetAccess',
       'StudyHoursPerWeek', 'Absences', 'PriorFailures', 'FinalGrade'],
      dtype='object')

Data Types
StudentID              int64
Gender                object
Age                    int64
ParentEducation       object
InternetAccess        object
StudyHoursPerWeek    float64
Absences               int64
PriorFailures          int64
FinalGrade           float64
dtype: object

Summary Statistics
         StudentID         Age  StudyHoursPerWeek    Absences  PriorFailures  \
count   315.000000  315.000000         295.000000  315.000000     315.000000
mean   2151.638095   22.146032          12.566102   14.612698       2.060317
std      86.242118    2.588117           6.900769    8.701480       1.411795
min    2001.000000   18.000000           1.000000    0.000000       0.000000
25%    2077.500000   20.000000           7.000000    7.000000       1.000000
50%    2151.000000   22.000000          13.000000   15.000000       2.000000
75%    2225.500000   25.000000          18.000000   22.000000       3.000000
max    2300.000000   26.000000          24.000000   29.000000       4.000000

       FinalGrade
count  295.000000
mean    53.315254
std     18.341960
min      4.000000
25%     40.500000
50%     53.000000
75%     66.000000
max    100.000000

#### Identify Issues in the Dataset
Looking at the dataset in Excel, the following standard changes need to made along with fixing missing and duplicated values:
- Values for the Gender should be "Male" or "Female"
- Values for the InternetAccess column should be "Yes", "No", or "Unknown"

In [ ]:
# Check for missing values
print("Missing Values")
print(df.isnull().sum())
print("")

# Check for duplicate rows
print("Duplicate Rows")
print(df.duplicated().sum())
print("")

# View the duplicate records
df[df.duplicated()]

Missing Values
StudentID             0
Gender                0
Age                   0
ParentEducation      57
InternetAccess       72
StudyHoursPerWeek    20
Absences              0
PriorFailures         0
FinalGrade           20
dtype: int64

Duplicate Rows
12

,StudentID,Gender,Age,ParentEducation,InternetAccess,StudyHoursPerWeek,Absences,PriorFailures,FinalGrade
301,2124,Female,25,Associate,No,21.0,16,3,74.0
302,2186,Female,23,Bachelor,No,1.0,7,2,41.0
303,2214,male,26,NaN,N,17.0,14,0,85.0
305,2128,male,22,High School,No,12.0,3,0,84.0
306,2177,Male,19,Bachelor,N,7.0,5,0,60.0
307,2074,Male,20,High School,No,7.0,10,3,46.0
308,2276,Female,22,High School,NaN,22.0,24,4,60.0
309,2243,Female,24,Bachelor,NaN,23.0,8,2,67.0
310,2267,Female,25,Associate,NaN,17.0,10,4,66.0
311,2148,Male,20,High School,NaN,2.0,5,1,53.0
312,2300,male,21,Master,NaN,9.0,10,0,53.0
314,2123,Male,20,Master,Yes,5.0,1,4,28.0

#### Data Cleaning

In [ ]:
# Fill in missing values
## Fill in missing values for ParentEducation with "Unknown"
df['ParentEducation'] = df['ParentEducation'].fillna('Unknown')

## Fill in missing values for InternetAccess with "Unknown"
df['InternetAccess'] = df['InternetAccess'].fillna('Unknown')

## Fill in missing values for StudyHoursPerWeek with the median
df['StudyHoursPerWeek'] = df['StudyHoursPerWeek'].fillna(df['StudyHoursPerWeek'].median())

## Drop the rows that are missing in FinalGrade
df = df.dropna(subset=['FinalGrade'])

# Standardize columns
## Standardize Gender column
df['Gender'] = df['Gender'].str.strip().str.title()

## Standardize InternetAccess column
df['InternetAccess'] = df['InternetAccess'].replace({'Y': 'Yes', 'N': 'No', 'Unknown': 'Unknown'})
df['InternetAccess'] = df['InternetAccess'].str.strip().str.title()

# Remove duplicates
df = df.drop_duplicates()

#### Final Check for Issues

In [ ]:
# Check for missing values
print("Missing Values")
print(df.isnull().sum())
print("")

# Check for duplicate rows
print("Duplicate Rows")
print(df.duplicated().sum())
print("")

# View the duplicate records
df[df.duplicated()]

Missing Values
StudentID            0
Gender               0
Age                  0
ParentEducation      0
InternetAccess       0
StudyHoursPerWeek    0
Absences             0
PriorFailures        0
FinalGrade           0
dtype: int64

Duplicate Rows
0

Empty DataFrame
Columns: [StudentID, Gender, Age, ParentEducation, InternetAccess, StudyHoursPerWeek, Absences, PriorFailures, FinalGrade]
Index: []

#### Final Dataset Inspection

In [ ]:
# Dataset dimesnions
print("Dataset Dimensions")
print("Rows and Columns: ", df.shape)
print("")

# Column names
print("Column Names")
print(df.columns)
print("")

# Data types
print("Data Types")
print(df.dtypes)
print("")

# Summary Statistics
print("Summary Statistics")
print(df.describe())

Dataset Dimensions
Rows and Columns:  (283, 9)

Column Names
Index(['StudentID', 'Gender', 'Age', 'ParentEducation', 'InternetAccess',
       'StudyHoursPerWeek', 'Absences', 'PriorFailures', 'FinalGrade'],
      dtype='object')

Data Types
StudentID              int64
Gender                object
Age                    int64
ParentEducation       object
InternetAccess        object
StudyHoursPerWeek    float64
Absences               int64
PriorFailures          int64
FinalGrade           float64
dtype: object

Summary Statistics
         StudentID         Age  StudyHoursPerWeek    Absences  PriorFailures  \
count   283.000000  283.000000         283.000000  283.000000     283.000000
mean   2148.759717   22.077739          12.734982   14.710247       2.074205
std      85.939441    2.587675           6.593873    8.677892       1.403443
min    2001.000000   18.000000           1.000000    0.000000       0.000000
25%    2074.500000   20.000000           7.000000    7.000000       1.000000
50%    2147.000000   22.000000          13.000000   15.000000       2.000000
75%    2220.500000   24.000000          17.500000   22.000000       3.000000
max    2300.000000   26.000000          24.000000   29.000000       4.000000

       FinalGrade
count  283.000000
mean    53.042403
std     18.376624
min      4.000000
25%     40.000000
50%     52.000000
75%     65.000000
max    100.000000

#### Save Cleaned Dataset

In [ ]:
df.to_csv('student_success_clean.csv', index=False)

#### Download Cleaned Dataset

In [ ]:
from google.colab import files
files.download('student_success_clean.csv')